[versions]
agp = "8.3.2"
kotlin = "1.9.0"
coreKtx = "1.13.1"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
material = "1.12.0"
fragment = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-fragment = {group = "androidx.fragment", name = "fragment", version.ref = "fragment"}
android-material = { group = "com.google.android.material", name = "material", version.ref = "material"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

